### ISSUE TITLE
页面生成后，如何通过js获取到当前的页码

### ISSUE THREAD

**Issue by epngllh** [eyblog/am-page#2]
页面生成后，如何通过js获取到当前的页码

**Comment by lscho** [comment]
通过js生成的可以使用生成的页码示例来获取
```javascript
    var page=$("#page1").page({ pages: 10 });
    console.log(page.option.curr)
```

在事件中可以用过 context.option.curr获取

如果通过data api生成的，目前只能通过获取li.am-active的index来得到当前页码

**Comment by wozl** [comment]
>
>`$("#page").page({`
		`curr:1,`
		`pages:10,`
		`prev:"上一页",`
		`next:"下一页",`
		`jump:function(){`
			`console.log(this.curr);`
		`}`
	`});`
>

可以通过这种方式在jump里面获取到动态的页码信息，相当于onChange事件，就可以达到类似于zui的分页器中的监听页码变化的时间，这里补充下
