### ISSUE TITLE
总页数

### ISSUE THREAD

**Issue by zhaojunliing** [eyblog/am-page#3]
当总页数为1时，不显示分页插件，怎么处理

**Comment by lscho** [comment]
总页数为1时我觉得好像没必要显示分页，所以代码里做了判断，总页码为1时不做任何处理

**Comment by zhaojunliing** [comment]
但是分页插件也不显示了，对于初始化表格，影响整体美观



suifengpiaoyanging@163.com
 
发件人： dameng
发送时间： 2017-07-31 15:46
收件人： lscho/am-page
抄送： zhaojunliing; Author
主题： Re: [lscho/am-page] 总页数 (#3)
总页数为1时我觉得好像没必要显示分页，所以代码里做了判断，总页码为1时不做任何处理

**Comment by lscho** [comment]
如果有这个需求的话，可以在`amazeui.page.js`第31行
```javascript
if(!option.pages||option.pages==1){
    return false;
}
```

中的`option.pages==1`这个判断去掉
