### ISSUE TITLE
for循环问题

### ISSUE THREAD

**Issue by zhaojunliing** [eyblog/am-page#4]
代码42行使用for(var i in )格式
建议使用for(var i=1;i<=option.pages;i++){

在js中，上面那个会产生一个undefined的按钮组件
测试是在chrome下

**Comment by lscho** [comment]
[http://jsrun.net/new](http://jsrun.net/new)  能不能在这里复现一下呢

**Comment by zhaojunliing** [comment]
说错行了，是82行。
试了试，没法重现，但是在我的环境中循环最后会有个remove值。

`		alert(JSON.stringify(list));
		// for (var i = 0 ; i< list.length ; i++) {
        for (var i in list) {
			alert(i);`

list 是正常的，[{"key":"first","value":"首页","page":1},{"key":1,"value":1,"page":1},{"key":"last","value":"尾页","page":1}]。

是不是哪里多出来了remove 属性。
这个网站是这样解释的。
http://www.cftea.com/c/2014/08/6290.asp


最后，谢谢你写的代码，帮助我解决了分页问题。
