### ISSUE TITLE
选择分页时候，会多次进入jump函数

### ISSUE THREAD

**Issue by ming54864** [eyblog/am-page#5]
多点几次后，会多次进入   jump函数 

 $.ajax({
            success: function (data) {
            var $page =$("#page").page({
                            pages: totalPage, //页数
                            curr: currPage, //当前页
                            jump: function(context, first) {
                                console.log('当前第：' + context.option.curr + "页" +",first="+first);
                            }
                        });
            }});

**Comment by lscho** [comment]
因为你这里的代码是在ajax的回调函数中生成的page实例，每一次ajax都会多生成一个，并且会多执行一次jump函数，和重复绑定事件是一样的，这里需要检测$page是否存在，存在的话就单独调用jump方法，不存在的话再生成page实例
