### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by fxk01** [eyblog/am-page#6]
分页怎么在渲染前重新加载呢

**Comment by lscho** [comment]
渲染前重新加载时什么意思？

**Comment by fxk01** [comment]
就是当pages是1的时候 重新AJAX接口后我想要把分页的标签删了

**Comment by lscho** [comment]
$page.remove() 方法可以移除组件。。。[demo](https://lscho.github.io/am-page/docs/demo.html) 的最下面有演示
